Diplo.GodMode.Testsite/ViewComponents/BananasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Extensions;

namespace Diplo.GodMode.Testsite.ViewComponents
{
    [ViewComponent(Name = "BananasList")]
    public class BananasViewComponent : ViewComponent
    {
        private readonly IPublishedContentQuery publishedContentQuery;

        public BananasViewComponent(IPublishedContentQuery publishedContentQuery)
        {
            this.publishedContentQuery = publishedContentQuery;
        }

        public async Task<IViewComponentResult> InvokeAsync(int maxItems = 3)
        {
            var items = GetRootContent().Take(maxItems);
            return View(items);
        }

        public IEnumerable<IPublishedContent> GetRootContent()
        {
            return publishedContentQuery.ContentAtRoot().SelectMany(x => x.Children());
        }
    }
}

Diplo.GodMode.Testsite/ViewComponents/RootContentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Extensions;

namespace Diplo.GodMode.Testsite.ViewComponents
{
    [ViewComponent(Name = "RootContentList")]
    public class RootContentViewComponent : ViewComponent
    {
        private readonly IPublishedContentQuery publishedContentQuery;

        public RootContentViewComponent(IPublishedContentQuery publishedContentQuery)
        {
            this.publishedContentQuery = publishedContentQuery;
        }

        public async Task<IViewComponentResult> InvokeAsync(int maxItems = 3)
        {
            var items = GetRootContent().Take(maxItems);
            return View(items);
        }

        public IEnumerable<IPublishedContent> GetRootContent()
        {
            return publishedContentQuery.ContentAtRoot().SelectMany(x => x.Children());
        }
    }
}

Diplo.GodMode.Testsite/Views/Blog.cshtml
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels

@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Blog>

@{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">

    <div class="container">

        <h3>Root Content List</h3>

        <vc:root-content-list max-items="2"></vc:root-content-list>

        @await Umbraco.RenderMacroAsync("latestBlogposts",
            new
            {
                numberOfPosts = Model.HowManyPostsShouldBeShown,
                startNodeId = Model.Id
            })
    </div>

</section>

Diplo.GodMode.Testsite/Views/Blogpost.cshtml
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels
@using Microsoft.AspNetCore.Mvc.Rendering
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Blogpost>
@{
    Layout = "master.cshtml";
}
@await Html.PartialAsync("~/Views/Partials/SectionHeader.cshtml")

<section class="section">
    <div class="container">
        <article>
            <div class="blogpost-meta">
                <small class="blogpost-date">@Model.CreateDate.ToShortDateString()</small>
                <span class="blogpost-cat">
                    @Html.Partial("~/Views/Partials/CategoryLinks.cshtml", Model.Categories)
                </span>
            </div>
            <h3>@Model.Excerpt</h3>
            @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            <!-- todo: implement discus comments -->
        </article>
    </div>
</section>

Diplo.GodMode.Testsite/Views/MacroPartials/FeaturedProducts.cshtml
@using Umbraco.Cms.Core.Models.PublishedContent
@using Umbraco.Cms.Core.Routing
@using Umbraco.Cms.Web.Common
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage
@inject UmbracoHelper Umbraco
@inject IPublishedValueFallback PublishedValueFallback
@inject IPublishedUrlProvider PublishedUrlProvider
@*
    This snippet lists the items from a Multinode tree picker, using the pickers default settings.
    Content Values stored as xml.

    To get it working with any site's data structure, set the selection equal to the property which has the
    multinode treepicker (so: replace "PropertyWithPicker" with the alias of your property).
*@

@{ var selection = Model.Content.Value<IEnumerable<IPublishedContent>>(PublishedValueFallback, "PropertyWithPicker").ToArray(); }

<ul>
    @foreach (var id in selection)
    {
        var item = Umbraco.Content(id);
        <li>
            <a href="@item.Url(PublishedUrlProvider)">@item.Name</a>
        </li>
    }
</ul>

Diplo.GodMode.Testsite/Views/MacroPartials/LatestBlogposts.cshtml
@using Microsoft.AspNetCore.Http
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels
@using Microsoft.AspNetCore.Mvc.Rendering
@using Umbraco.Cms.Core.Routing
@using Umbraco.Cms.Web.Common
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage
@inject UmbracoHelper Umbraco
@inject IPublishedUrlProvider PublishedUrlProvider
@inject IHttpContextAccessor HttpContextAccessor
@{
    var startNodeId = Model.MacroParameters["startNodeId"] ?? Model.Content.Id;

    var numberOfPosts = 3;
    if (Model.MacroParameters["numberOfPosts"] != null)
    {
        int.TryParse((string)Model.MacroParameters["numberOfPosts"], out numberOfPosts);
    }
}

@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.Content(startNodeId);

    if (startNode == null)
    {
        <div class="blogposts">
            <h1>There are no posts at this time, try again later.</h1>
        </div>

        return;
    }

    var httpContext = HttpContextAccessor.HttpContext;

    //Gets all blogposts to calculate pages
    var blogposts = startNode.Children.OrderBy(x => x.CreateDate).ToList();
    var pageCount = (int)Math.Ceiling((double)blogposts.Count / (double)numberOfPosts);
    //gets the page from the querystring and sets it to one if it is out of range
    var page = 1;
    if (httpContext != null && !string.IsNullOrEmpty(httpContext.Request.Query["page"]))
    {
        int.TryParse(httpContext.Request.Query["page"], out page);
        if (page <= 0 || page > pageCount)
        {
            page = 1;
        }
    }
    //Gets the blogposts for the current page
    var pagedBlogposts = blogposts.Skip((page - 1) * numberOfPosts).Take(numberOfPosts).ToList();

    if (pagedBlogposts.Count > 0)
    {
        <div class="blogposts">

            @foreach (ContentModels.Blogpost post in pagedBlogposts)
            {
                <a href="@post.Url(PublishedUrlProvider)" class="blogpost">
                    <div class="blogpost-meta">
                        <small class="blogpost-date">@post.CreateDate.ToShortDateString()</small>
                        <small class="blogpost-cat">
                            @await Html.PartialAsync("~/Views/Partials/CategoryLinks.cshtml", post.Categories)
                        </small>
                    </div>
                    <h3 class="blogpost-title">@post.PageTitle</h3>
                    <div class="blogpost-excerpt">@post.Excerpt</div>
                </a>
            }
        </div>
    }

    if (blogposts.Count > numberOfPosts)
    {
        <div class="pagination">
            <nav class="nav-bar nav-bar--center">
                @if (page <= 1)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Prev</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url(PublishedUrlProvider) + "?page=" + (page - 1))">Prev</a>
                }

                @for (int i = 1; i <= pageCount; i++)
                {
                    <a class="nav-link nav-link--black @(page == i ? " nav-link--active" : null)" href="@(Model.Content.Url(PublishedUrlProvider) + "?page=" + i)">@i</a>
                }
                @if (page == pageCount)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Next</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url(PublishedUrlProvider) + "?page=" + (page + 1))">Next</a>
                }

            </nav>
        </div>
    }
}

Diplo.GodMode.Testsite/Views/Partials/CategoryLinks.cshtml
@model IEnumerable<string>
@foreach (var category in Model)
{
    <!-- TODO: Add links to categories-->
    @category
    <text> </text>
}

Diplo.GodMode.Testsite/Views/Partials/ContactForm.cshtml
@using Umbraco.Extensions
@using Umbraco.SampleSite
@model Umbraco.SampleSite.ContactFormViewModel

@{
    var message = TempData["Message"]?.ToString();
}
<div class="form-group">
@using (Html.BeginUmbracoForm<ContactFormController>(nameof(ContactFormController.Submit)))
{
    <div>
        @Html.TextBoxFor(m => m.Name, new {@class="form-control", placeholder = Html.DisplayNameFor(m => m.Name)})
        @Html.ValidationMessageFor(m => m.Name)
    </div>
    <div>
        @Html.TextBoxFor(m => m.Email, new {@class="form-control", placeholder = Html.DisplayNameFor(m => m.Email)})
        @Html.ValidationMessageFor(m => m.Email)
    </div>
    <div>
        @Html.TextAreaFor(m => m.Message, new {@class="form-control", placeholder = Html.DisplayNameFor(m => m.Message)})
        @Html.ValidationMessageFor(m => m.Message)
    </div>
    <input type="submit" name="Submit" value="Submit"/>
   @if (!string.IsNullOrEmpty(message))
   {
       @message
   }
}
</div>

Diplo.GodMode.Testsite/Views/Partials/Navigation/SubNavigation.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@using Umbraco.Cms.Core.Models.PublishedContent
@using Umbraco.Cms.Core.Routing
@using Umbraco.Extensions

@inject IPublishedValueFallback PublishedValueFallback
@inject IPublishedUrlProvider PublishedUrlProvider
@{
    var siteSection = Model.AncestorOrSelf(2);
    var selection = siteSection.Children.Where(x => x.IsVisible(PublishedValueFallback));
}

@foreach (var item in selection)
{
    <a class="nav-link nav-link--black nav-link--air-bottom @(item.IsAncestorOrSelf(Model) ? "nav-link--active" : null)" href="@item.Url(PublishedUrlProvider)">@item.Name</a>
}

Diplo.GodMode.Testsite/Views/Partials/Navigation/TopNavigation.cshtml
@using Umbraco.Cms.Core.Models.PublishedContent
@using Umbraco.Cms.Core.Routing
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
    var site = Model.Root();
    var selection = site.Children.Where(x => x.IsVisible());
}
<!-- comment out the following line if you want to remove the root node name from the top navigation -->
<a class="nav-link @Html.Raw(Model.Id == site.Id ? "navi-link--active" : "")" href="@site.Url()">@site.Name</a>
@foreach (var item in selection)
{
    <a class="nav-link @(item.IsAncestorOrSelf(Model) ? "nav-link--active" : null)" href="@item.Url()">@item.Name</a>
}

Diplo.GodMode.Testsite/Views/Partials/SectionHeader.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
<section class="section section--themed section--header section--content-center-bottom">
    <div class="section__hero-content">
        <h1 class="no-air">@Model.GetProperty("PageTitle").GetValue()</h1>
    </div>
</section>

Diplo.GodMode.Testsite/Views/Partials/Testies.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage

<h3>This is a test partial!!!</h3>

Diplo.GodMode.Testsite/Views/Partials/blocklist/default.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (Model?.Any() != true) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("blocklist/Components/" + data.ContentType.Alias, block)
    }
</div>

Diplo.GodMode.Testsite/Views/Partials/grid/bootstrap3-fluid.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@*
    Razor helpers located at the bottom of this file
*@

@if (Model is JObject && Model?.sections is not null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row);
                    }
                </div>
            }
        }
        else
        {
            <div class="row clearfix">
                @foreach (var sec in Model.sections)
                {
                    <div class="grid-section">
                        <div class="col-md-@sec.grid column">
                            @foreach (var row in sec.rows)
                            {
                                renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row)
    {
        <div @RenderElementAttributes(row)>
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
        </div>
    }
}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Diplo.GodMode.Testsite/Views/Partials/grid/bootstrap3.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is JObject && Model?.sections is not null)
{
  var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row, true);
                    }
                </div>
            }
        }
        else
        {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var sec in Model.sections)
                    {
                        <div class="grid-section">
                            <div class="col-md-@sec.grid column">
                                @foreach (var row in sec.rows)
                                {
                                    renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row, bool singleColumn)
    {
        <div @RenderElementAttributes(row)>
            @if (singleColumn) {
                @:<div class="container">
            }
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
            @if (singleColumn) {
                @:</div>
            }
        </div>
    }

}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null)
        {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Diplo.GodMode.Testsite/Views/Partials/grid/editors/base.cshtml
@model dynamic

@try
{
    string editor = EditorView(Model);
    <text>@await Html.PartialAsync(editor, Model as object)</text>
}
catch (Exception ex)
{
    <pre>@ex.ToString()</pre>
}

@functions{

    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.Replace(".html", ".cshtml");

        if (!view.Contains("/"))
        {
            view = "grid/editors/" + view;
        }

        return view;
    }
}

Diplo.GodMode.Testsite/Views/Partials/grid/editors/embed.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is not null)
{
  string embedValue = Convert.ToString(Model.value);
  embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;

  <div class="video-wrapper">
    @Html.Raw(embedValue)
  </div>
}

Diplo.GodMode.Testsite/Views/Partials/grid/editors/macro.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model?.value is not null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    var parameters = new Dictionary<string,object>();
    foreach (var mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @await Umbraco.RenderMacroAsync(macroAlias, parameters)
    </text>
}

Diplo.GodMode.Testsite/Views/Partials/grid/editors/media.cshtml
@model dynamic
@using Umbraco.Cms.Core.Media
@using Umbraco.Cms.Core.PropertyEditors.ValueConverters
@inject IImageUrlGenerator ImageUrlGenerator

@if (Model?.value is not null)
{
    var url = Model.value.image;

    if (Model.editor.config != null && Model.editor.config.size != null)
    {
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">

    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Diplo.GodMode.Testsite/Views/Partials/grid/editors/rte.cshtml
@using Umbraco.Cms.Core.Templates
@model dynamic
@inject HtmlLocalLinkParser HtmlLocalLinkParser;
@inject HtmlUrlParser HtmlUrlParser;
@inject HtmlImageSourceParser HtmlImageSourceParser;

@{
    var value = HtmlLocalLinkParser.EnsureInternalLinks(Model?.value.ToString());
    value = HtmlUrlParser.EnsureUrls(value);
    value = HtmlImageSourceParser.EnsureImageSources(value);
}

@Html.Raw(value)

Diplo.GodMode.Testsite/Views/Partials/grid/editors/textstring.cshtml
@using System.Web
@model dynamic

@if (Model?.editor.config.markup is not null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaks((string)Model.value.ToString()).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model?.editor.config.style">@Model?.value</div>
    </text>
}

Diplo.GodMode.Testsite/Views/Person.cshtml
@{
	Layout = "master.cshtml";
}
<p>Nothing to see, but we could make a lesson to display a person</p>

<partial name="/Views/Partials/SectionHeader.cshtml" />

Diplo.GodMode.Testsite/Views/Product.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Product>
@{
    Layout = "master.cshtml";
    var defaultCurrency = Model.Parent<Products>().DefaultCurrency;
}
<!-- for the section we want to show the shop header -->
@Html.Partial("~/Views/Partials/SectionHeader.cshtml", Model.Parent)

@await Component.InvokeAsync("RootContentList", new { maxItems = 3 })

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="product-image-container">
                    <img class="product-image" src="@Model.Photos?.Url()" alt="@Model.ProductName image" />
                </div>
            </div>
            <div class="col-md-6">
                <h1>@Model.ProductName</h1>
                <div class="product-price">@defaultCurrency @Model.Price.ToString("F")</div>
                <div class="product-teaser">@Model.Description</div>
                <div class="product-button">
                    <button class="button button--border--solid">Buy</button>
                </div>
                <div class="product-advantages">
                    @if (Model.Features != null)
                    {
                        foreach (var feature in Model.Features)
                        {
                            <div class="product-advantage">
                                <h4>@feature.FeatureName</h4>
                                <h5>@feature.FeatureDetails</h5>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section section--sand">
    <div class="container">
        <!-- todo: Check if grid is empty via a property value converter -->
        @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
    </div>
</section>

Diplo.GodMode.Testsite/Views/Shared/Components/BananasList/Default.cshtml
@model IEnumerable<IPublishedContent>

<h3>Beatrix is Bananas!!!</h3>
<ul>
    @foreach (var item in Model)
    {
        <li><a href="@item.Url()">@item.Name</a></li>
    }
</ul>

Diplo.GodMode.Testsite/Views/contentPage.cshtml
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ContentPage>
@{
    Layout = "master.cshtml";
}

<partial name="/Views/Partials/SectionHeader.cshtml" />

<section class="section">

    <div class="container">

        <div class="col-md-3">
            <nav class="nav-bar nav-bar--list">

                <partial name="Navigation/SubNavigation"></partial>

                @await Component.InvokeAsync("RootContentList", new { maxItems = 3 })

                <vc:bananas-list></vc:bananas-list>



            </nav>
        </div>

        <div class="col-md-9">
            <article>
                @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            </article>
        </div>
    </div>

</section>

Diplo.GodMode.Testsite/Views/people.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<People>
@{
    Layout = "master.cshtml";
}
@{
    void SocialLink(string content, string service)
    {
        if (!string.IsNullOrEmpty(content))
        {
            ; //semicolon needed otherwise <a> cannot be resolved
            <a class="employee-grid__item__contact-item" href="http://@(service).com/@content">@service</a>
        }
    }
}

@await Html.PartialAsync("SectionHeader")

        <partial name="/Views/Partials/Testies.cshtml" />

        <vc:bananas-list max-items="12"></vc:bananas-list>

<section class="section">

    <div class="container">
        <!-- todo: implement department filter -->
        <!--
        <nav class="nav-bar nav-bar--center nav-bar--air-bottom">
            <a class="nav-link nav-link--black nav-link--active" href="">All</a>
            <a class="nav-link nav-link--black" href="">Marketing</a>
            <a class="nav-link nav-link--black" href="">Package People</a>
            <a class="nav-link nav-link--black" href="">Designers</a>
            <a class="nav-link nav-link--black" href="">Other</a>
        </nav>
        -->
        <div class="employee-grid">
            @foreach (Person person in Model.Children<Person>())
            {

                <div class="employee-grid__item">
                    <div class="employee-grid__item__image" style="background-image: url('@person.Photo?.Url()')"></div>
                    <div class="employee-grid__item__details">
                        <h3 class="employee-grid__item__name">@person.Name</h3>
                        @if (!string.IsNullOrEmpty(person.Email))
                        {
                            <a href="mailto:@person.Email" class="employee-grid__item__email">@person.Email</a>
                        }
                        <div class="employee-grid__item__contact">
                            @{ SocialLink(person.FacebookUsername, "Facebook"); }
                            @{ SocialLink(person.TwitterUsername, "Twitter"); }
                            @{ SocialLink(person.LinkedInUsername, "LinkedIn"); }
                            @{ SocialLink(person.InstagramUsername, "Instagram"); }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</section>